### ISSUE TITLE
Use `add-to-project` action to classify the issues

### ISSUE THREAD

**Issue by Belco90** [octoclairvoyant/octoclairvoyant-webapp#1079]
### What feature would you like to have?

Set up the [GitHub Action `add-to-project`](https://github.com/actions/add-to-project) so all the issues are tracked through GitHub Projects.

### What problem will this feature solve?

By having the issues tracked within GitHub Projects, it would be easier to triage the tickets, follow the bugs pending to be fixed, feature requests or internal improvements.

### Do you want to help make the feature?

Yes

**Comment by HonkingGoose** [comment]
Yeah having the issues on our project board would make managing things easier.

The Action is still at a `0.x` version though, so it will likely having breaking changes on updates. So that's a thing to keep in mind before we jump in.

**Comment by Belco90** [comment]
Good point. I'll keep an eye on the action to see how evolves and will revisit this in the future.

**Comment by Belco90** [comment]
I've been checking the releases, and it seems pretty stable to me. I'll put something in a PR later to see how it works.
