### ISSUE TITLE
Are the status labels still needed?

### ISSUE THREAD

**Issue by Belco90** [octoclairvoyant/octoclairvoyant-webapp#1106]
### What feature would you like to have?

We have some `status:<state>` labels across the repo which are automatically assigned when certain actions happen (issue created, PR created, etc).

Since we have the same info in GitHub Projects, are those labels still necessary? It seems like an info duplication to me, but maybe there is a reason to keep them that I'm missing.

/cc @HonkingGoose 

### What problem will this feature solve?

N/A

### Do you want to help make the feature?

Yes

**Comment by HonkingGoose** [comment]
I basically copied the `status:*` labels from Renovate. But now that we're using the project boards, we can drop them if you want. 😉

**Comment by Belco90** [comment]
I'm tracking the projects and tickets state through GH Projects, so the labels are not that useful for me anymore.  If that's the case for you too, I'll proceed to delete such labels. Can you confirm this?

**Comment by HonkingGoose** [comment]
Yes, you can delete the labels you don't like anymore. 😉
