### ISSUE TITLE
Prepare backend to enable Heroicons

### ISSUE THREAD

**Issue by HonkingGoose** [octoclairvoyant/octoclairvoyant-webapp#148]
## About Heroicons

The icons I use in the mockup are from: https://heroicons.com/

They have React components: https://github.com/tailwindlabs/heroicons#react

Heroicons should not change size in any way, as they are designed to look their best at fixed sizes.

If we need to emphasize a icon, I will add some background color with padding on it, to make the icon appear bigger, without actually changing the icon size. 😉

## Rules to use Heroicons:

- The Outline icons are for primary navigation and marketing sections, and should stay at 24x24 pixels
- The Solid icons are for buttons, form elements and to support text, should be rendered at 20x20 pixels.

## What I can help with

I think once you've done the work to setup the code so that I can import the icons into the components, I can change out the icons we have now with appropriate ones from Heroicons.

**Comment by Belco90** [comment]
I'm working on this one. I just realized that [the `react-icons` package we use already includes Heroicons](https://react-icons.github.io/react-icons/icons?name=hi)! I'll replace some icons with the Heroicons versions for this PR then.
