### ISSUE TITLE
Swap Chakra UI icons with Heroicons

### ISSUE THREAD

**Issue by HonkingGoose** [octoclairvoyant/octoclairvoyant-webapp#153]
## What feature would you like to have?

Once we are ready to use the new Heroicons in the code, we can start using them.

## What problem will be solved by having the feature?

The icons will look nicer.
We do need to take care to use them at their intended sizes.

## Do you want to help making the feature?

I hope to do the work of swapping the Chakra UI icons with the nicer Heroicons.

I will need one example though, so I can see how to import and use the icon in the component code. 😉

**Comment by HonkingGoose** [comment]
Blocked until issue #148 is done.

**Comment by Belco90** [comment]
I think this one is done already? In #148 I switched available icons with the Heroicons alternatives.

**Comment by HonkingGoose** [comment]
We're using the `react-icons/hi` nearly everywhere now.

The only place where we use a different icon set is for the GitHub login button component, that uses `react-icons/di` (devicons):

https://github.com/octoclairvoyant/octoclairvoyant-webapp/blob/349a0259dc840e2a320987c439868e992da27395/src/components/GitHubLoginButton.tsx#L3

The Heroicons doesn't have a GitHub logo icon.

I already did some basic design work on a replacement modal for the GitHub login, that uses a official GitHub provided logo.

I think we can close this issue now.
