### ISSUE TITLE
Remove Cancel Workflow Action

### ISSUE THREAD

**Issue by Belco90** [octoclairvoyant/octoclairvoyant-webapp#1564]
### What internal change would you like to have?

It doesn’t seem it makes sense to use the [Cancel Workflow Action](https://github.com/marketplace/actions/cancel-workflow-action) in combination with the new GitHub merge queue.

Let’s remove it.

### What problem will this change solve?

Avoid cancelling pipelines for main branch when using the new [merge queue](https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/), which I enabled for this repo.

### Do you want to help make the feature?

Yes

**Comment by HonkingGoose** [comment]
Are you sure Merge Queue is working for you? I don't see any merges via the queue: https://github.com/octoclairvoyant/octoclairvoyant-webapp/queue/main

From reading the GitHub Docs, it looks like you need to add `merge_group:` to the GitHub Action files, so it runs the tests on the merge queue branches. [^docs]

```yaml
on:
  pull_request:
  merge_group:
```

[^docs]: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions

**Comment by Belco90** [comment]
@HonkingGoose I actually wasn't sure if some extra config was needed, so I wanted to take advantage of this PR to investigate it. Thanks for pointing the missing set up! I'll make sure it is configures properly when I open the PR.

**Comment by HonkingGoose** [comment]
I've written the documentation to get Renovate and GitHub Merge Queue working, see:

https://docs.renovatebot.com/key-concepts/automerge/#github-merge-queue

**Comment by Belco90** [comment]
> @Belco90 I see you got the GitHub Merge Queue working on the repository, at least when you're manually adding Renovate PRs to the queue.

Yes! Renovate docs really helped me with it.
