### ISSUE TITLE
Create automated tests

### ISSUE THREAD

**Issue by HonkingGoose** [octoclairvoyant/octoclairvoyant-webapp#177]
## What feature would you like to have?

We don't run any automated test on our components, or on the website as a whole.

I think we would benefit from having some basic tests (even if it's just to confirm that a certain text actually shows on a rendered page), or that our comparator actually works.

## What problem will be solved by having the feature?

Reduce manual review work, improve confidence we're not breaking things when we update dependencies, or update our code.

## Do you want to help making the feature?

I'm willing to help out, but I don't know how get to Jest or Cypress set up for use with our Next.js app.
Also I need some "templates" or basic tests that I can then try enhancing.

**Comment by Belco90** [comment]
I had this in mind and have implemented tons of tests with both Jest and Cypress for Next.js projects in the past. It was just a matter of time, but definitely I still interested in implementing them.

There are tons of examples within Next.js repo, so you can find some references there about how to set it up with Jest. This is an example with Jest + TS: https://github.com/vercel/next.js/blob/canary/examples/with-typescript-eslint-jest/README.md

**Comment by HonkingGoose** [comment]
Do we still want to add more tests, or are we happy with having just the Cypress tests for now? I'm not able to work on any Jest tests, as I've not really written any new Jest tests ever.

**Comment by Belco90** [comment]
I think we can consider this ticket done.

There are more things related to testing we can address in other tickets tho:

- Stubbing requests in Cypress (already has a ticket)
- Unit/integration tests with Jest + Testing Library
- Visual diff testing

**Comment by HonkingGoose** [comment]
I've created issues for the remaining items, see:

- #510
- #511

Closing this issue now. 😄
