### ISSUE TITLE
Optimize font loading within Next.js 12 (either by hand or automatically)

### ISSUE THREAD

**Issue by HonkingGoose** [octoclairvoyant/octoclairvoyant-webapp#203]
## What feature would you like to have?

Currently we load in the Google fonts normally, so without any `DNS prefetching` or `preconnect` properties within the`<link>` tag.
Google fonts does give those properties in the link it generates when you select fonts from them.

We don't yet know if we need to add `DNS Prefetching` and `preconnect` properties ourselves, or if Next.js 11 does this for us.

## What problem will be solved by having the feature?

Loading the fonts should be faster with `DNS prefetching` and `preconnect` enabled

## Do you want to help making the feature?

I tried figuring out if Next.js 11 does this out of the box for us, but searching their docs and repository wasn't helping clarify things.

See PR #197 for the full discussion we had earlier.

**Comment by Belco90** [comment]
This is definitely optimized already.

**Comment by HonkingGoose** [comment]
Cool, we don't have to do anything then. 😄
