### ISSUE TITLE
Migrate tests to Vitest

### ISSUE THREAD

**Issue by Belco90** [octoclairvoyant/octoclairvoyant-webapp#2098]
### What internal change would you like to have?

Migrate the integration tests from Jest to Vitest. [Migration guide here](https://vitest.dev/guide/migration.html#migrating-from-jest).

### What problem will this change solve?

Vitest is faster and modern. Also, we wouldn't face [issues with MSW.js](https://mswjs.io/docs/migrations/1.x-to-2.x#requestresponsetextencoder-is-not-defined-jest).

### Do you want to help make the feature?

Yes

**Comment by HonkingGoose** [comment]
By the way, in the Renovate repository, `@zharinov` made the Jest tests faster with the `--shard` option. See this issue and related PRs for more information:

- https://github.com/renovatebot/renovate/issues/14572
- https://github.com/renovatebot/renovate/pull/22644
- https://github.com/renovatebot/renovate/pull/22721

Or you can go ahead with the migration to Vitest, and see how that works. Maybe they have something similar to `--shard`. :smile:

**Comment by Belco90** [comment]
@HonkingGoose thanks for the suggestion! I already used jest shard option in a different project with thousands of tests. That's not the case here, we have only 2 integration tests files. It's more about using a more modern syntax, ESM compatible, and using faster transpiler under the hood.

**Comment by HonkingGoose** [comment]
Yeah, it's a bit silly to set up sharding when we only have two test files. 🙂
