### ISSUE TITLE
Override default tokens with new tokens

### ISSUE THREAD

**Issue by HonkingGoose** [octoclairvoyant/octoclairvoyant-webapp#244]
## What feature would you like to have?

> Override default tokens with new tokens

## What problem will be solved by having the feature?

> Having tons of color tokens would add unnecessary complexity, especially if we don't use the main tokens.

## Do you want to help making the feature?

I don't fully understand what we need to change, so I'll stay away for now. 😄 

Issue #243 will need to be done before we can start working on this issue, I think.

**Comment by Belco90** [comment]
I just ran into this tool 🤯 https://www.hyperthe.me/

I didn't have time to check it properly but if it help us to customize the theme with ease for both of us, I'm happy to pay the pro version.

**Comment by Belco90** [comment]
This is **exactly** what we need to define our text variant colors for both light and dark themes

https://twitter.com/NikolovLazar/status/1486445592729591818
