### ISSUE TITLE
Bad background behavior on large viewport heights

### ISSUE THREAD

**Issue by HonkingGoose** [octoclairvoyant/octoclairvoyant-webapp#262]
### Describe the bug

Page background on Homepage (`/`) does not fully extend to the footer.

### Give the steps to reproduce

1. Open homepage.
2. Open browser devTools, go to responsive design mode
3. Enter viewport height: `2000`
4. See really large white background appear between feature list and footer

### What browsers are you seeing the problem on?

Firefox

### Have you thought of a possible solution?

No

### Do you want to help fix the bug?

No

**Comment by Belco90** [comment]
I believe this is fixed now. @HonkingGoose can you confirm this, please?

**Comment by HonkingGoose** [comment]
It's fixed, I cannot reproduce the problem anymore.

**Comment by Belco90** [comment]
Thanks for confirming!
