### ISSUE TITLE
Set background color per page

### ISSUE THREAD

**Issue by HonkingGoose** [octoclairvoyant/octoclairvoyant-webapp#270]
### What feature would you like to have?

In my Figma design I made the assumption that we use 4 page background colors at most.

- A light shade of coolGray for the homepage (so the feature list really pops out).
- A slightly darker shade of coolGray for the comparator (so it's easier on the eyes).

- A fully saturated coolGray for the homepage in dark mode (makes everything pop out)
- A slightly less saturated coolGray for the comparator screen.

The design frequently assumes that a component will have the same background color as the whole page.
Right now our code doesn't not support this workflow, which leads to weird styling bugs like #262.

I'm not sure how we can set the page background, but I think Chakra UI does support this via their theme customization options.

### What problem will this feature solve?

Use 4 consistent page background colors, allow components to use "transparent" as background.
Most of the components in Figma should lay flat on our background, so it's easiest if we only define the background color once, instead of changing it for each component.

### Do you want to help make the feature?

Yes

### Is there anything else we need to know?

I'm wiling to help, but don't know how.... 😄 

I've picked our page backgrounds in the Figma design, so really the only thing left to do is to make the code changes to support the new workflow. 😄

**Comment by Belco90** [comment]
I think we can set this up also in `Layout` component, which is reused across all pages.

**Comment by HonkingGoose** [comment]
> I think we can set this up also in `Layout` component, which is reused across all pages.

I tried doing something like:

```typescript
<Layout as="coolGray.50">
```

But that just caused TypeScript to complain at me. So maybe this is possible if you know what you're doing, but I couldn't get it working. 😄

**Comment by Belco90** [comment]
TypeScript complaints are right here! Remember that [the `as` prop is to set the HTML tag you want to render](https://chakra-ui.com/docs/features/style-props#the-as-prop).

To change the background color, you should use [`bgColor` prop](https://chakra-ui.com/docs/features/style-props#color-and-background-color), and you can do that directly within `Layout.tsx` component in the `Box` wrapping the children:

```js
// ...
<Box mt={{ base: 4, md: 8 }} flex="1 0 auto" bgColor="coolGray.50">
  {children}
</Box>
```
