### ISSUE TITLE
Unit/integration tests with Jest + Testing Libary

### ISSUE THREAD

**Issue by HonkingGoose** [octoclairvoyant/octoclairvoyant-webapp#510]
### What feature would you like to have?

We probably should have some unit/integration tests which use Jest + Testing Library. Relying on Cypress for most tests will be too slow, and will not test the internals of the app.

### What problem will this feature solve?

Increased confidence in the app.

### Do you want to help make the feature?

Yes

**Comment by Belco90** [comment]
Follow [this guide](https://nextjs.org/docs/testing#setting-up-jest-with-the-rust-compiler) when the time comes.
