### ISSUE TITLE
Visual diff testing

### ISSUE THREAD

**Issue by HonkingGoose** [octoclairvoyant/octoclairvoyant-webapp#511]
### What feature would you like to have?

Right now we need to test manually to see if the layout/visuals of the app change whenever we update our dependencies.

I think we could probably do some sort of "visual snapshot" testing?

### What problem will this feature solve?

Increased confidence updates do not break our layout/visuals.

### Do you want to help make the feature?

Yes

**Comment by Belco90** [comment]
A couple of interesting resources for this:

- [How to actually test UIs](https://storybook.js.org/blog/how-to-actually-test-uis/): an interesting comparison of different testing resources for checking your UI
- [How to automate UI tests with Github Actions](https://storybook.js.org/blog/how-to-automate-ui-tests-with-github-actions/): useful examples to setup GitHub Actions with Cypress + Storybook + Chromatic

**Comment by Belco90** [comment]
I'm gonna give Applitools a try for this: https://docs.cypress.io/guides/tooling/visual-testing#Tooling
