### ISSUE TITLE
Replace custom components with Chakra UI customized components styles

### ISSUE THREAD

**Issue by Belco90** [octoclairvoyant/octoclairvoyant-webapp#515]
We have some components extending Chakra UI ones in order to customize the base style provided by this library.

Instead of having such custom components, we can use [Chakra UI customizing component styles](https://chakra-ui.com/docs/theming/customize-theme#customizing-component-styles).

Those components are:
- `CTAButton`: this should be replaceable by using regular Chakra `Button` + custom `"cta"` variant
- `FluidContainer`: Chakra already added `Container` component, so we can use that one + customized default values instead
- `Link`: we can use the default `Link` + customized default color instead of our custom component

Apart from removing unnecessary custom components, this ticket will help me to figure out how to customize tokens and defaults from the theme, to achieve things like setting the default light/dark background in all pages, default light/dark text color, etc.

**Comment by HonkingGoose** [comment]
> Apart from removing unnecessary custom components, this ticket will help me to figure out how to customize tokens and defaults from the theme, to achieve things like setting the default light/dark background in all pages, default light/dark text color, etc.

Cool! 🥳 🎈
