### ISSUE TITLE
Migrate from Yarn 1 to npm 8

### ISSUE THREAD

**Issue by Belco90** [octoclairvoyant/octoclairvoyant-webapp#544]
### What feature would you like to have?

We need to migrate from Yarn v1 into something else.

[We could migrate to Yarn v3](https://yarnpkg.com/getting-started/migration), although I'm not a huge fan of v2/3 changes, to be honest. [You also need npm itself to run some commands now](https://yarnpkg.com/getting-started/migration#cli-commands).

npm is a great option now, so we could migrate to npm v8 since 1) it's needed by Yarn v3 for some commands, 2) it's the default package manager you get when installing node, and 3) seems a less-risky option.

What do you think @HonkingGoose?

### What problem will this feature solve?

[The yarn 1.x line is frozen](https://github.com/yarnpkg/yarn,) so it would be great to migrate to something else.

### Do you want to help make the feature?

Yes

**Comment by HonkingGoose** [comment]
> We need to migrate from Yarn v1 into something else.

Agree!

> [We could migrate to Yarn v3](https://yarnpkg.com/getting-started/migration), although I'm not a huge fan of v2/3 changes, to be honest. [You also need npm itself to run some commands now](https://yarnpkg.com/getting-started/migration#cli-commands).

If we need `npm` anyway, then I propose we use `npm` instead of installing a separate package manager like `yarn`.

> npm is a great option now, so we could migrate to npm v8 since 1) it's needed by Yarn v3 for some commands, 2) it's the default package manager you get when installing node, and 3) seems a less-risky option.

Agree!

> What do you think @HonkingGoose?

I agree we should migrate, but I'm thinking about which package manager - and which version - Renovate bot supports best. I'll go do some research to try to figure this out.

**Comment by HonkingGoose** [comment]
The maintainer of Renovate suggest we use either Yarn 3 or npm 8. On that basis I'd suggest for us to migrate to npm 8 as that removes the Yarn dependency.

- https://github.com/renovatebot/renovate/discussions/12581

**Comment by Belco90** [comment]
Thanks for checking this out so quickly!

I agree, let's move to npm v8 so we get rid of an extra dependency. I'll take care of it during the week.
