### ISSUE TITLE
Group Renovate dependencies to limit test runs

### ISSUE THREAD

**Issue by HonkingGoose** [octoclairvoyant/octoclairvoyant-webapp#673]
### What feature would you like to have?

Adjust Renovate configuration so it will group common dependencies together.

| Grouping | Security critical | Update frequency |
| --- | --- | --- |
| Next.js, React (Framework stack) | yes | daily |
| ESLint, Prettier, ESLint plugins | not likely | monthly |
| Jest, Cypress, and testing utils | not likely |  monthly |
| Chakra UI, emotion, and Framer Motion | not likely | monthly |
| React Query + Octokit | not likely | monthly |
| Rehype + Remark ecosystem | not likely | monthly |
| TypeScript, TS types, and type-fest | not likely | monthly |
| lint-staged and husky | not likely | monthly |

### What problem will this feature solve?

Right now whenever we have a update PR, and the PR branch gets behind `main`, Renovate will "rebase" so that it's current with `main`. This causes the tests to run again.
It gets even worse when we have more than one update PR ready to go, because all other PR branches get "rebased" as well.

~We're going to use Percy to test for visual changes, but we do not get unlimited resources, so we will need to be smart about the amount of runs we do.~

By grouping updates into logical buckets, we can reduce the amount of PRs that Renovate will create. This will help reduce the amount of "rebase" actions that Renovate performs.

If we want a update ahead of schedule, we can request it from the Dependency Dashboard.

### Do you want to help make the feature?

Yes

### Is there anything else we need to know?

Relevant Renovate docs:

- https://docs.renovatebot.com/noise-reduction/#package-grouping
- https://docs.renovatebot.com/noise-reduction/#selective-scheduling

**Comment by Belco90** [comment]
What is the state for this ticket? It would be great to decrease the frequency to upgrade the mentioned packages.

**Comment by HonkingGoose** [comment]
I keep putting off doing the work to get the config going, because I'm scared of getting it wrong. I'm asking for help from the Renovate maintainers, so I can finally get this done. 🙈 

- https://github.com/renovatebot/renovate/discussions/17266

**Comment by Belco90** [comment]
Fair enough, no rush!
