### ISSUE TITLE
Revamp the webapp: static parts

### ISSUE THREAD

**Issue by Belco90** [octoclairvoyant/octoclairvoyant-webapp#710]
### What feature would you like to have?

It's time to apply the new design of the webapp. I'll try to do this in different parts:

1. Common parts (header and footer basically)
2. Landing page
3. Comparator page (this will have to be split into smaller parts too, but I'll figure that out later).

### What problem will this feature solve?

Apply the new design that we have in Figma to the actual webapp.

### Do you want to help make the feature?

Yes

### Is there anything else we need to know?

This is basically a placeholder ticket. I'll be creating small PRs linked here to iterate through these tasks:

- [X] Common parts --> #736 
- [x] Landing page --> #777
- [x] Comparator page --> Moved to #1105

**Comment by HonkingGoose** [comment]
@Belco90 I don't think we're done with this issue (yet)? I see two more to-do's on your list. 😉

**Comment by Belco90** [comment]
Not yet! Sorry, it was autoclosed by the reference from the first PR.

**Comment by Belco90** [comment]
Repurposing this ticket to just revamping the static parts, so it can be closed. The revamp of the comparator page has been moved to this new ticket #1105
