### ISSUE TITLE
Opening a link with "&to=latest" doesn't render

### ISSUE THREAD

**Issue by astellingwerf** [octoclairvoyant/octoclairvoyant-webapp#924]
### Describe the bug

When navigating to a 🐙 🔮  page with the "to" query parameter set to "latest" the page doesn't work properly. For example: https://octoclairvoyant.vercel.app/comparator?repo=renovatebot%2Frenovate&from=32.52.2&to=latest

I'm sure this worked a few weeks ago.

### Give the steps to reproduce

1. Select your favorite project
2. Choose a previous version for "from release"
3. Choose a specific release for "to release"
4. Notice that the page renders fine
5. Reload the page
6. Notice that the page renders fine
7. Choose "latest" for "to release"
8. Notice that the page renders fine
9. Release the page
10. Notice the error: "No processed releases to show"

### What browsers are you seeing the problem on?

Chrome

### Have you thought of a possible solution?

No

### Do you want to help fix the bug?

No

### Is there anything else we need to know?

Love the project! It's a great service, complementary to Renovate when the logs aren't available in a Renovate-compatible way.

**Comment by HonkingGoose** [comment]
You're right, something's going wrong here.
When I open the browser console after going to your link, I see this error:

```
TypeError: Invalid Version: latest
    c semver.js:25
    exports compare-build.js:3
    exports diff.js:23
    a release.tsx:60
    u runtime.js:46
    a runtime.js:275
    b runtime.js:98
    l release.tsx:1
    c release.tsx:1
instrument.js:110
```

Steps to reproduce:

1. Click on https://octoclairvoyant.vercel.app/comparator?repo=renovatebot%2Frenovate&from=32.52.2&to=latest
1. Open browser console
1. See TypeError

**Comment by Belco90** [comment]
@astellingwerf thanks for reporting this! I think it may be related to changes introduced in #831. I'll try to look at this during the week.
