### ISSUE TITLE
Update to Cypress `v10`

### ISSUE THREAD

**Issue by HonkingGoose** [octoclairvoyant/octoclairvoyant-webapp#973]
### What feature would you like to have?

Update our Cypress test framework to `v10`.

### What problem will this feature solve?

Use the new Cypress app.

- Automatic migration from previous Cypress versions
- Change browsers from within the Cypress app
- Improved error messages
- Optional: use component testing (beta)

### Do you want to help make the feature?

No

### Is there anything else we need to know?

Run `cypress open` to follow the interactive migration.

Some breaking changes:

- `cypress.json` config file no longer supported, replace with `cypress.config.js` or `cypress.config.ts` file
- Cypress configuration file is now required
- `cypress open` can no longer "Run all specs" or "Run filtered specs"
- You can only run tests on Cypress-supported browsers

**Comment by Belco90** [comment]
I've created a PR to make [`@types/happo-cypress` compatible with Cypress v10](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61026) so we can go ahead with this upgrade.

**Comment by Belco90** [comment]
> I've created a PR to make [`@types/happo-cypress` compatible with Cypress v10](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61026) so we can go ahead with this upgrade.

This has been merged! Migration to Cypress v10 is unblocked now.
