### ISSUE TITLE
Use prettier's `--cache` option to speed up runs

### ISSUE THREAD

**Issue by HonkingGoose** [octoclairvoyant/octoclairvoyant-webapp#974]
### What feature would you like to have?

Prettier `2.7.0` comes with a new `--cache` option. We should try it out. 😉 

### What problem will this feature solve?

When you use Prettier's `--cache` option it only checks files that have been _changed_. This can speed up the Prettier run quite a bit.

On Gitpod or GitHub Codespaces there's no speed-up, because you start from scratch. So this is only helpful for people who develop locally.

### Do you want to help make the feature?

Yes

### Is there anything else we need to know?

[Prettier docs, `--cache`](https://prettier.io/docs/en/cli.html#--cache)

Wait until Renovate updates us to Prettier `v2.7.0`, or higher.

**Comment by Belco90** [comment]
We can take advantage of the cache in CI too if we save it between runs, but I don't think we would get faster runs since the codebase is quite small.

**Comment by HonkingGoose** [comment]
> We can take advantage of the cache in CI too if we save it between runs, but I don't think we would get faster runs since the codebase is quite small.

@Belco90 Do you know how you can use the Prettier cache in the CI? That would speed up the runs on the Renovate repository a lot, I think.

**Comment by Belco90** [comment]
> @Belco90 Do you know how you can use the Prettier cache in the CI? That would speed up the runs on the Renovate repository a lot, I think.

I think so! You need the [`actions/cache` GitHub Action](https://github.com/actions/cache). With this plugin, you can cache builds or dependencies (pretty much everything), so you can specify the folder where Prettier saves its internal cache.

From what I see in Prettier docs, by default it's located in `./node_modules/.cache/prettier/.prettier-cache`, and there is no option to customize the path (for now at least), so you would have to set that specific folder in the `actions/cache` after installing the project dependencies (so the `node_modules` don't override your Prettier cache).
