### ISSUE TITLE
Rewrite selector for failing test

### ISSUE THREAD

**Issue by HonkingGoose** [octoclairvoyant/octoclairvoyant-webapp#982]
### What feature would you like to have?

Ignore failing end to end test, re-enable test once the upstream bug is fixed.

### What problem will this feature solve?

The test is failing on every PR, and it's not helping us decide if we should merge anymore.

### Do you want to help make the feature?

No

### Is there anything else we need to know?

Follow issue:

- https://github.com/testing-library/cypress-testing-library/issues/222

File with failing test: https://github.com/octoclairvoyant/octoclairvoyant-webapp/blob/main/cypress/integration/404.spec.ts

**Comment by Belco90** [comment]
I need to rewrite the selector failing, so we can keep the test, just with a different way of querying the proper element.

**Comment by HonkingGoose** [comment]
Dang it. 😉 At least you tried to fix it by using the Cypress-native commands. 😄
